Repository mate-app/mate_app, pull requests merged in 2020-12, with the labels that each got.

#3 Issue#1
  lib/views/calendar/calendar.dart
  lib/views/full_setup/views/login.dart
Labels: bug

#7 Issue#5
  lib/shared/error_message.dart
  lib/shared/shared.dart
  lib/views/cafeteria/cafeteria.dart
  lib/views/calendar/calendar.dart
  lib/views/full_setup/views/subjects.dart
  lib/views/news/news.dart
  lib/views/organisation/organisation.dart
Labels: invalid

#8 small typo was the problem
  lib/views/cafeteria/local_widgets/cafeteria_list_panel.dart
Labels: bug

#10 moved id check to separate condition
  lib/views/organisation/organisation.dart
Labels: bug

#13 Issue#11
  ios/Flutter/.last_build_id
  lib/models/usermodel.dart
  lib/views/settings/settings.dart
  lib/views/settings/settings_account/local_widgets/settings_account_properties.dart
  lib/views/settings/settings_account/local_widgets/settings_account_votediagram.dart
  lib/views/settings/settings_version/settings_version.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#14 new privacy text
  lib/views/settings/settings_privacy/settings_privacy.dart
Labels: enhancement

#15 android Icons
  android/app/src/main/mate_launcher-playstore.png
  android/app/src/main/res/mipmap-anydpi-v26/mate_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/mate_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/mate_launcher.png
  android/app/src/main/res/mipmap-hdpi/mate_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/mate_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/mate_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/mate_launcher.png
  android/app/src/main/res/mipmap-mdpi/mate_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/mate_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/mate_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/mate_launcher.png
  android/app/src/main/res/mipmap-xhdpi/mate_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/mate_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/mate_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/mate_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/mate_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/mate_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/mate_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/mate_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/mate_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/mate_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/mate_launcher_round.png
Labels: enhancement
